import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#00296b',
  },
header: {
  height: 190, 
  width: '100%',
  position: 'relative', 
  overflow: 'hidden',
  backgroundColor: 'red', 
},
backgroundImage: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  width: '100%',
  height: '100%',
  resizeMode: 'cover', 
},
  backgroundOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
backgroundColor: 'rgba(4, 49, 122, 0.9)'
  },
  satelliteContainer: {
    position: 'absolute',
    top: -50,
    right: -50,
    width: 200,
    height: 200,
    zIndex: 1,
  },
  satelliteBeams: {
    position: 'absolute',
    top: 80,
    right: 80,
    width: 120,
    height: 120,
    backgroundColor: 'transparent',
    borderRadius: 60,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    shadowColor: '#ffffff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  headerContent: {
    zIndex: 2,
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 15,
  },
  greeting: {
    color: 'white',
    fontSize: 24,
    fontWeight: '300',
  },
  weatherContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  weatherIcon: {
    fontSize: 20,
    marginRight: 5,
  },
  temperature: {
    color: 'white',
    fontSize: 20,
    fontWeight: '400',
  },
  profileContainer: {
    marginTop: 10,
    position: 'relative',
  },
  profileImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: 'white',
  },
  profileInitial: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  dropdown: {
    position: 'absolute',
    top: 60,
    right: 0,
    backgroundColor: 'white',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    minWidth: 150,
    zIndex: 1000,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  dropdownText: {
    color: '#333',
    fontSize: 14,
    fontWeight: '500',
  },
  companyName: {
    color: 'white',
    fontSize: 11,
    fontWeight: '500',
    marginBottom: 15,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationIcon: {
    fontSize: 16,
    marginRight: 8,
    marginTop: 2,
  },
  locationLabel: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 12,
  },
  locationText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#fff',
    marginVertical: 10,
  },
  optionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  optionCard: {
    backgroundColor: 'white',
    width: '48%',
    padding: 20,
    borderRadius: 12,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    position: 'relative',
  },
  driverLabel: {
    position: 'absolute',
    top: 10,
    right: 15,
    color: '#999',
    fontSize: 10,
    fontStyle: 'italic',
  },
  optionIcon: {
    alignItems: 'center',
    marginBottom: 2,
  },
  profileIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileIconText: {
    color: 'white',
    fontSize: 20,
  },
  carIcon: {
    fontSize: 40,
  },
  reportIcon: {
    fontSize: 40,
  },
  securityIcon: {
    fontSize: 40,
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#e36414',
    marginBottom: 8,
    textAlign: 'center',
  },
  optionSubtitle: {
    fontSize: 11,
    color: '#666',
    textAlign: 'center',
    lineHeight: 16,
  },
  customerCareContainer: {
    marginTop: 0,
    marginBottom: 30,
  },
  customerCareLabel: {
    fontSize: 12,
    color: '#999',
    fontStyle: 'italic',
    marginBottom: 10,
  },
  customerCareCard: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  customerCareIcon: {
    marginBottom: 2,
  },
  supportIcon: {
    fontSize: 50,
  },
  customerCareTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#e36414',
    marginBottom: 8,
    textAlign: 'center',
  },

  // En tu archivo homeStyles
logoImage: {
  width: '100%',
  height: '100%',
  borderRadius: 50, // Esto la hace redonda (ajusta el valor según el tamaño)
},
  customerCareSubtitle: {
    fontSize: 11,
    color: '#666',
    textAlign: 'center',
    lineHeight: 16,
  },
  footer: {
    paddingVertical: 20,
  },
  logoutButton: {
    backgroundColor: '#dc2626',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    alignItems: 'center',
  },
  logoutText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
});