import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1e3a8a',
  },
  header: {
    backgroundColor: '#1e3a8a',
    paddingBottom: 80,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    alignItems: 'center',
    position: 'relative',
    zIndex: 1,
  },
  backButton: {
    position: 'absolute',
    left: 10,
    borderRadius: 8,
    padding: 8,
  },
  avatarContainer: {
    marginBottom: 15,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  companyName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
  },
  scrollContent: {
    flex: 1,
    marginTop: 0,
    backgroundColor: '#f5f5f5',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  infoSection: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginTop: -60,
    marginBottom: 20,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 2,
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f3be9dff',
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#e36414',
    marginLeft: 8,
  },
  infoContent: {
    paddingHorizontal: 18,
    paddingTop: 5,
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 10,
  },
  infoLabel: {
    fontSize: 16,
    marginRight: 12,
    width: 24,
    textAlign: 'center',
  },
  infoText: {
    fontSize: 14,
    color: '#303030ff',
    flex: 1,
  },
  menuSection: {
    marginHorizontal: 20,
    marginTop: 20,
  },
  menuItem: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 18,
    marginBottom: 12,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuText: {
    fontSize: 14,
    color: '#333',
    marginLeft: 12,
    fontWeight: '500',
  },
  chevronRight: {
    transform: [{ rotate: '180deg' }],
  },
  avatarImage: {
    width: 50,
    height: 50,
    borderRadius: 20,
    resizeMode: 'cover',
  },
  // Estilos para la sección de versión profesional
  versionContainer: {
    paddingVertical: 0,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginTop: 10,
  },
  versionDivider: {
    width: 70,
    height: 2,
    backgroundColor: '#e36414',
    borderRadius: 2,
    marginBottom: 10,
  },
  companyInfoContainer: {
    alignItems: 'center',
    marginBottom: 0,
  },
  companyNameBold: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1e3a8a',
    letterSpacing: 1,
    marginBottom: 4,
  },
  versionSubtext: {
    fontSize: 12,
    color: '#464545ff',
    fontWeight: '500',
  },
  versionDetailsContainer: {
    width: '100%',
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    gap: 4,
  },
  versionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 1,
  },
  versionLabel: {
    fontSize: 12,
    color: '#464545ff',
    fontWeight: '500',
  },
versionValue: {
  fontSize: 13,
  color: '#1e3a8a',
  fontWeight: '600',
},
  copyrightText: {
    fontSize: 11,
    color: '#575757ff',
    textAlign: 'center',
    fontStyle: 'italic',
    marginTop: 5,
  },
});